version: "3.8"
services:
  stellar:
    image: stellar/quickstart:testing
    ports:
      - "8000:8000"
    command: --standalone --enable-soroban-rpc
    volumes:
      - stellar-data:/opt/stellar
volumes:
  stellar-data:

